### ISSUE TITLE
components Architecture 

### ISSUE THREAD

**Issue by alikhleel** [Team15-kfupm/myRewards-Angular#18]
I propose an architecture that we would like to follow it up in the next sprint.

![Untitled Diagram drawio(1)](https://user-images.githubusercontent.com/23135660/220175478-99234cd8-44b5-431a-aaa4-22227247c36d.png)

Give you your opinion.

**Comment by Ali-jdk** [comment]
Sounds real good

**Comment by alikhleel** [comment]
Done with it
