### ISSUE TITLE
Redeem Offer 

### ISSUE THREAD

**Issue by Ali-jdk** [Team15-kfupm/myRewards-Angular#21]
I made a redeem offer UI for the BO instead of generating it 
Taking that form our last meeting with the team 

the code must be generated from the user UI and the BO just redeem it 

Here is the UI:

https://user-images.githubusercontent.com/61953059/221243386-5ce68e03-e6f5-49fe-8e85-22bac006b06e.mov

**Comment by alikhleel** [comment]
We have change the logic of validating promo code. and merged #23  to the main.
