### ISSUE TITLE
Add Dedicated Login Button for Cashiers on Auth Page

### ISSUE THREAD

**Issue by alikhleel** [Team15-kfupm/myRewards-Angular#31]
a dedicated button should be provided for cashiers to access their login page instead of requiring them to manually enter "/auth/cashier".  Currently we don't have this button and I don't know where it should be.

**Comment by Ali-jdk** [comment]
On it !

**Comment by Ali-jdk** [comment]
![Screenshot 2023-04-06 at 8 37 11 AM](https://user-images.githubusercontent.com/61953059/230281497-75600dec-df87-4d23-a11a-dadb4acc787a.png)
![Screenshot 2023-04-06 at 8 37 35 AM](https://user-images.githubusercontent.com/61953059/230281503-8a4a298c-ba46-4f0c-91ae-57b9724c4148.png)
![Screenshot 2023-04-06 at 8 37 52 AM](https://user-images.githubusercontent.com/61953059/230281508-5a07fa69-1d54-4a0e-a67e-ddbd6958ca42.png)


Give me you comments

**Comment by Ali-jdk** [comment]
It will be in the same page with the regular login with just a click it will change the form from the regular login to the cashier's login !
