### ISSUE TITLE
Blank Page on Offer Page When No Offers Available

### ISSUE THREAD

**Issue by alikhleel** [Team15-kfupm/myRewards-Angular#33]
It seems like there's a problem on the offer page. When there are no offers for the user, instead of showing a message that says "create an offer", the page appears blank. This can be confusing and frustrating for users. To make things better, we should fix this problem and show a clear message that tells the user there are no offers and encourages them to create one.

**Comment by Ali-jdk** [comment]
Sure

**Comment by Ali-jdk** [comment]
![Screenshot 2023-04-06 at 7 51 16 AM](https://user-images.githubusercontent.com/61953059/230274933-13b6456b-145b-448c-9ba8-7afbd8190bd1.png)


Don't hesitate if you have any comments !

**Comment by alikhleel** [comment]
Well done,
If you done with this issue close it.

Note: that you can link this issue with the modified branch using the '#' symbol. You can easily reference and manage the issue in question.

**Comment by alikhleel** [comment]
I've tried it, actually it is a nice update in the UI.
There are some small problems with the new cashier form:
- 'generate OTP' button gets bigger when the spinner appears
- email validation does not work
- It would be nice if you view an indication that OTP is incorrect

**Comment by alikhleel** [comment]
I like the new login page, it looks really cool! But I found some problems with the cashier form. The 'generate OTP' button becomes bigger when the spinner is there, and it seems like the email check doesn't work. It would be nice if there was a way to tell when the OTP is wrong.

**Comment by alikhleel** [comment]
Let me know if there's anything I can do to assist with resolving them
